# Generated by Django 5.0.4 on 2024-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("course_code", models.CharField(max_length=20)),
                ("course_title", models.CharField(max_length=255)),
                ("credit_hours", models.IntegerField()),
                ("time_building_room", models.CharField(max_length=255)),
                ("final_exam_datetime", models.DateTimeField()),
                ("instructor", models.CharField(max_length=100)),
                ("remarks", models.CharField(max_length=255)),
            ],
        ),
    ]
